# Generated by Django 3.2.14 on 2022-10-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uaMedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звезды рейтинга', 'verbose_name_plural': 'Звезды рейтинга'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='film_actor', to='uaMedia.Actor', verbose_name='актеры'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(default='2022', verbose_name='Дата выхода'),
        ),
    ]
